tabular:
  output_folder: output/tabular
  path: data/sample.csv
  preprocessing:
    add_row_id: true
    categorical_encoding:
      columns:
        - gender
        - city
      method: onehot
    cleaning:
      lowercase: true
      remove_special_chars: false
      trim_strings: true
    column_filtering:
      drop: []
      keep:
        - age
        - income
        - gender
        - city
    drop_duplicates: true
    dtype_conversion:
      age: int
      gender: category
      income: float
    missing_values:
      columns:
        age: 30
        name: Unknown
      global_fill: null
    normalization:
      columns:
        - age
        - income
      method: minmax
    outlier_removal:
      columns:
        - age
        - income
      method: iqr
      threshold: 1.5
    remove_empty_columns: true
    rename_columns:
      oldName: new_name
      productID: product_id
  type: csv

images:
  path: data/images
  output_folder: output/images
  preprocessing:
    grayscale: true
    normalize: true
    resize:
      - 128
      - 128

videos:
  output_folder: output/video_frames
  path: data/videos/sample.mp4
  preprocessing:
    extract_frames: 30
    resize_frames:
      - 64
      - 64
